### ISSUE TITLE
Module resolution broken in v1.19.0 for Node.js ESM projects

### ISSUE THREAD

**Issue by KevinForys** [box/box-typescript-sdk-gen#760]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

This appears to be similar to issue #759. I'm upgrading my pure Node.js ESM project dependencies from Box TypeScript SDK **v1.16.0** to **v1.19.0**, and my project won't build anymore due to a module resolution error.

The error path shows a duplicated path (`/lib/lib/`) and double `.js.js` extension, which suggests a module resolution issue introduced in recent versions. The same code works perfectly in production with v1.16.0 but breaks immediately after upgrading to v1.19.0.

### Steps to Reproduce

1. Have a working Node.js ESM project with Box TypeScript SDK v1.16.0
2. Use the following import code:
   ```javascript
   const {
     BoxOAuth,
     OAuthConfig,
   } = require('box-typescript-sdk-gen/lib/box/oauth.generated.js');
   
   this.oauth = new BoxOAuth({ config: config });
   ```
3. Upgrade Box TypeScript SDK from v1.16.0 to v1.19.0
4. Try to run/build the project
5. See MODULE_NOT_FOUND error

### Expected Behavior

The module should be resolved correctly as it was in v1.16.0, and the application should run without any import/require errors.

### Error Message, Including Stack Trace

```
node:internal/modules/cjs/loader:643
      throw e;
      ^
Error: Cannot find module '/node_modules/box-typescript-sdk-gen/lib/lib/box/oauth.generated.js.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1249:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1237:15)
    at resolveExports (node:internal/modules/cjs/loader:636:14)
    at Module._findPath (node:internal/modules/cjs/loader:716:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
  code: 'MODULE_NOT_FOUND',
  path: '/node_modules/box-typescript-sdk-gen/package.json'
}
```

### Screenshots

N/A

### Versions Used

**Typescript SDK:** v1.19.0 (previously working with v1.16.0)  
**Platform:** Node.js (Pure ESM project)  
**Node.js (if applicable):** v20.19.3  
**npm:** v11.5.2
